import { NextRequest, NextResponse } from 'next/server';

/**
 * GET /api/parent/notifications
 *
 * Read-only endpoint for parent to view their ward's notifications.
 * In production, this would verify parent session and return associated student's notifications.
 *
 * Query Parameters:
 * - sessionToken: string - Parent session token from OTP login
 *
 * Response:
 * - Success: 200 with { success: true, data: NotificationData }
 * - Error: 400/401/405 with { message: string }
 *
 * Permissions: READ-ONLY - No mutation allowed
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const sessionToken = searchParams.get('sessionToken');

    // Validate session token
    if (!sessionToken) {
      return NextResponse.json(
        { message: 'Authentication required. Please login again.' },
        { status: 401 }
      );
    }

    // Decode and verify session token (mock implementation)
    let tokenData;
    try {
      const decoded = Buffer.from(sessionToken, 'base64').toString('utf-8');
      tokenData = JSON.parse(decoded);
    } catch (error) {
      return NextResponse.json(
        { message: 'Invalid session token' },
        { status: 401 }
      );
    }

    // Verify role is PARENT
    if (tokenData.vertical !== 'parent' && tokenData.role !== 'parent') {
      return NextResponse.json(
        { message: 'Access denied. Parent access required.' },
        { status: 403 }
      );
    }

    // Check token expiration (24 hours)
    const tokenAge = Date.now() - tokenData.timestamp;
    const maxAge = 86400000; // 24 hours in milliseconds

    if (tokenAge > maxAge) {
      return NextResponse.json(
        { message: 'Session expired. Please login again.' },
        { status: 401 }
      );
    }

    // Mock notification data - in production, query database for parent's associated student
    const notifications = [
      {
        id: '1',
        title: 'Fee Payment Reminder',
        message: 'Semester 2 hostel fees of ₹30,000 are due on 31 December 2025.',
        type: 'fee',
        date: '2025-12-25',
        read: false,
      },
      {
        id: '2',
        title: 'Leave Application Approved',
        message: 'Winter vacation leave from 20-25 December 2025 has been approved.',
        type: 'leave',
        date: '2025-12-20',
        read: true,
      },
      {
        id: '3',
        title: 'Room Inspection Notice',
        message: 'Scheduled room inspection on 15 January 2025. Please ensure room is tidy.',
        type: 'general',
        date: '2025-12-18',
        read: true,
      },
      {
        id: '4',
        title: 'Winter Schedule',
        message: 'Mess timings during winter vacation: Breakfast 7-9 AM, Lunch 12-2 PM, Dinner 7-9 PM.',
        type: 'general',
        date: '2025-12-15',
        read: true,
      },
    ];

    const notificationSummary = {
      total: notifications.length,
      unread: notifications.filter(n => !n.read).length,
      read: notifications.filter(n => n.read).length,
    };

    const notificationData = {
      summary: notificationSummary,
      items: notifications,
    };

    // Mock logging
    console.log('\n========================================');
    console.log('🔔 PARENT NOTIFICATIONS ACCESS');
    console.log('========================================');
    console.log('Endpoint: /api/parent/notifications');
    console.log('Session ID:', tokenData.sessionId || 'unknown');
    console.log('Total Notifications:', notificationSummary.total);
    console.log('Unread:', notificationSummary.unread);
    console.log('Access Type: READ-ONLY');
    console.log('========================================\n');

    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 100));

    return NextResponse.json({
      success: true,
      data: notificationData,
    });

  } catch (error) {
    console.error('Error in /api/parent/notifications:', error);
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * POST, PUT, DELETE, PATCH - Disallowed mutations
 * This endpoint is READ-ONLY
 * Notifications are generated by the system, not by parents.
 */
export async function POST() {
  return NextResponse.json(
    { message: 'Method not allowed. This endpoint is read-only. Notifications are system-generated.' },
    { status: 405 }
  );
}

export async function PUT() {
  return NextResponse.json(
    { message: 'Method not allowed. This endpoint is read-only.' },
    { status: 405 }
  );
}

export async function DELETE() {
  return NextResponse.json(
    { message: 'Method not allowed. This endpoint is read-only.' },
    { status: 405 }
  );
}

export async function PATCH() {
  return NextResponse.json(
    { message: 'Method not allowed. This endpoint is read-only.' },
    { status: 405 }
  );
}
